---
   
  - name: Print java keytool var
    debug: var=java_keytool_exec verbosity=3

  - name: Print java keystore_path var
    debug: var=keystore_path verbosity=3

  - name: fail if java_keytool_exec not specified
    fail: 
      msg: "java_keytool_exec not specified...cannot do anything."
    when: java_keytool_exec is not defined or java_keytool_exec == ""

  - name: fail if java_keystore_path not specified
    fail: 
      msg: "java_keystore_path not specified...cannot do anything."
    when: java_keystore_path is not defined or java_keystore_path == ""

  - name: Clear the command params
    set_fact:
      command_to_exec: ['{{ java_keytool_exec }}']

  - name: append commad params
    set_fact:
      command_to_exec: "{{ command_to_exec }} + [ '-list' ] + [ '-v' ]"

  - name: append keystore_path param
    set_fact:
      command_to_exec: "{{ command_to_exec }} + [ '-keystore' ] + [ '{{ java_keystore_path }}' ]"
    when: java_keystore_path is defined and java_keystore_path != ""

  - name: append storetype param
    set_fact:
      command_to_exec: "{{ command_to_exec }} + [ '-storetype' ] + [ '{{ java_keystore_type }}' ]"
    when: java_keystore_type is defined and java_keystore_type != ""

  - name: append storepass param
    set_fact:
      command_to_exec: "{{ command_to_exec }} + [ '-storepass' ] + [ '{{ java_keystore_password }}' ]"
    no_log: "{{ not ( disable_no_log | default(false,true) ) }}"
    when: java_keystore_password is defined and java_keystore_password != ""

  - name: Print the command that we're going to run
    debug:
      msg: "About to run: {{ command_to_exec|join(' ') }}"

  - name: execute command - list aliases in keystore
    command:
      argv: "{{ command_to_exec }}"
    register: cmd_result
    no_log: "{{ not ( disable_no_log | default(false,true) ) }}"

  - name: Print the cmd_result to the console.
    debug:
      msg: "{{ cmd_result.stdout_lines | join('\n') }}"