---

- include_tasks: command_native.yaml
  vars:
    webmethods_script_dir: "{{ webmethods_install_dir }}/API_Portal/server/bin/"
    webmethods_script_start: "./CloudAgentApp.sh"
    webmethods_script_start_params: "start"
    webmethods_script_stop: "./CloudAgentApp.sh"
    webmethods_script_stop_params: "stop"