---

  - name: "Print loop vars"
    debug:
      msg: "Checking access to ports {{ validation_ports | join(',') }} on host={{ outer_item }}"
      verbosity: 1
    when: validation_ports is defined and (validation_ports|length > 0)

  - name: Wait for validation ports to become open on the host, don't start checking for {{ validation_ports_delay }} seconds
    wait_for:
      host: "{{ outer_item }}"
      port: "{{ item }}"
      delay: "{{ validation_ports_delay }}"
      timeout: "{{ validation_ports_timeout }}"
    with_items: "{{ validation_ports }}"
    when: validation_ports is defined and (validation_ports|length > 0)