---

  - name: Set changed flag to false if not defined
    set_fact: 
      configure_integrationserver_wxconfig_enable_package_changed: false
    when: configure_integrationserver_wxconfig_enable_package_changed is not defined

  - name: fail if wxconfig_params_target_package_name not specified
    fail: 
      msg: "wxconfig_params_target_package_name not specified...cannot create."
    when: wxconfig_params_target_package_name is not defined or wxconfig_params_target_package_name == ""

  - name: Create main wxconfig controller file if not there already
    file:
      path: "{{ wxconfig_target_package_config_path }}/wxconfig.cnf"
      state: touch

  - name: Enable this new config in the main controller file
    lineinfile:
      path: "{{ wxconfig_target_package_config_path }}/wxconfig.cnf"
      regexp: '^{{ item.key }}'
      insertafter: '^#{{ item.key }}'
      line: "{{ item.key }}={{ item.value }}"
    register: "result_wxconfig_controller_operation"
    with_dict: "{{ wxconfig_params_global_configs }}"

  - name: Set changed flag to true if any mutating operation did change
    set_fact: 
      configure_integrationserver_wxconfig_enable_package_changed: true
    when: result_wxconfig_controller_operation.changed == true

  - name: Print the changed var
    debug:
      var: configure_integrationserver_wxconfig_enable_package_changed
      verbosity: 2